variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
buildAndRun:win:debug:
  script:
    - mkdir build
    - cd build
    - cmake -G Ninja -DBUILD_CORE_ONLY=1 -DCMAKE_BUILD_TYPE=Debug ..
    - ninja cbl
    - .\cbl.exe ../src/tests/general.clj
    # - .\cbl.exe ../src/tests/loader.clj
    - .\cbl.exe ../src/tests/variables.clj
    - .\cbl.exe ../src/tests/subchains.clj
    - .\cbl.exe ../src/tests/linalg.clj
  tags:
    - WIN, BOOST, MINGW

buildAndRun:win:release:  
  script:
    - mkdir build
    - cd build
    - cmake -G Ninja -DBUILD_CORE_ONLY=1 -DCMAKE_BUILD_TYPE=Release ..
    - ninja cbl
    - .\cbl.exe ../src/tests/general.clj
    # - .\cbl.exe ../src/tests/loader.clj
    - .\cbl.exe ../src/tests/variables.clj
    - .\cbl.exe ../src/tests/subchains.clj
    - .\cbl.exe ../src/tests/linalg.clj
  tags:
    - WIN, BOOST, MINGW
