[package]
name = "shards-ml"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.5.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
tokenizers = { version = "0.19.1", default-features = false, features = [
  "onig",
] }

candle-core = { version = "0.6.0" }
candle-transformers = { version = "0.6.0" }
candle-nn = { version = "0.6.0" }

metal = { version = "0.27.0", features = ["mps"], optional = true }
cudarc = { version = "0.12.0", features = ["std", "cublas", "cublaslt", "curand", "driver", "nvrtc", "f16", "cuda-version-from-build-system", "dynamic-linking"], default-features=false, optional = true }
accelerate-src = { version = "0.3.2", optional = true }
libc = { version = "0.2.147", optional = true }

serde_json = "1.0.102"
once_cell = "1.9.0"

[features]
default = []
metal = ["dep:metal", "candle-core/metal", "candle-transformers/metal", "candle-nn/metal"]
cuda = ["dep:cudarc", "candle-core/cuda", "candle-transformers/cuda", "candle-nn/cuda"]
accelerate = ["dep:accelerate-src", "dep:libc", "candle-core/accelerate", "candle-transformers/accelerate", "candle-nn/accelerate"]
