[package]
name = "shards-network"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.4.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
tokio-tungstenite = {version = "^0.20.1", features = ["native-tls"]}
tungstenite = {version = "^0.20.1", features = ["native-tls"]}
slotmap = "1.0"
futures = "*"
url = "*"
futures-util = "*"
hyper = {version = "^1.1.0", features = ["server"]}
hyper-util = {version = "0.1.2", features = ["full"]}
http-body-util = "0.1"
http = "*"
nanoid = "*"
reqwest = "*"
log = "*"
anyhow = "^1.0.70"

[dependencies.tokio]
version = "*"
features = ["sync", "macros", "net", "fs"]

[build-dependencies]
bindgen = "0.69"
