[package]
name = "shards-fs"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.4.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
rfd = { version = "0.11", git = "https://github.com/shards-lang/rfd.git", tag = 'shards-1', default-features = false, optional = true}

[features]
default = []
rfd-enabled = ["rfd"]
rfd-xdg = ["rfd/xdg-portal"]
rfd-gtk3 = ["rfd/gtk3"]
