[package]
name = "shards-physics"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.5.0"
shards = { path = "../../rust" }
rapier3d = { version = "0.17.2" }
crossbeam = { version = "0.8.2" }
compile-time-crc32 = "0.1.2"
