accepted = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "Zlib",
    "ISC",
    "OFL-1.1", # NotoEmoji-Regular inside egui (https://github.com/emilk/egui/issues/2321)
    "LicenseRef-UFL-1.0" # The ubuntu fonts inside egui (https://github.com/emilk/egui/issues/2321)
]
