[package]
name = "shards-sqlite"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
shards = { path = "../../rust" }
crsql_bundle = { path = "../../../deps/sqlite/cr-sqlite/core/rs/bundle", features = [
    "static",
] }
