[package]
name = "shards-sqlite"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.4.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
cozo = { version = "0.7.6", default-features = false, features = ["storage-sqlite"] }

[features]
default = []
cozo-full = ["cozo/graph-algo"]