[package]
name = "shards-db"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.4.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
cozo = { version = "0.7.6", default-features = false, features = ["graph-algo", "storage-sqlite"] }

[features]
default = []