[package]
name = "shards-onnx"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.4.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
tract-onnx = { version = "0.20.19-pre" , git = "https://github.com/shards-lang/tract.git" }
