[package]
name = "gfx"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []
tracy = ["profiling/profile-with-tracy", "tracy-client"]

[dependencies]
wgpu-native = { path = "../wgpu-native", default-features = false, features = ["wgsl", "spirv", "dx12", "metal"] }
wgpu-core = { path = "../wgpu/wgpu-core" }
wgpu-types = { path = "../wgpu/wgpu-types" }
naga-native = { path = "../naga-native"}
profiling = { version = "1", default-features = false }
tracy-client = { version = "0.15.0", optional = true }

[patch.crates-io]
objc = { git = "https://github.com/shards-lang/rust-objc.git", branch = "shards-0.2.7" }
metal = { git = "https://github.com/shards-lang/metal-rs.git", branch = "shards-0.28.0" }
naga = { path = "../wgpu/naga" }

# Until updates tracy-client to 0.15.0 (https://github.com/aclysma/profiling/pull/44)
profiling = { path = "../profiling" }
tracy-client = { git = "https://github.com/nagisa/rust_tracy_client", tag = "tracy-client-v0.15.0" }

[patch."https://github.com/gfx-rs/naga"] 
naga = { path = "../wgpu/naga" }

[patch."https://github.com/gfx-rs/wgpu"]
wgpu-types = { path = "../wgpu/wgpu-types" }
wgpu-core = { path = "../wgpu/wgpu-core" }

[build-dependencies]
cbindgen = "0.24.0"

[workspace]
members = []

# The profile settings are required to get reasonable performance
# some validations are enabled by default based on debug-assertions
# including synchronization validation which adds about 60ms every frame
[profile.rel-with-deb-info]
debug-assertions = false
debug = true
opt-level = 0

[profile.rel-with-deb-info.package."*"]
debug-assertions = false
debug = true
opt-level = 0

# [profile.rel-with-deb-info.package."wgpu-hal"]
# debug-assertions = false
# debug = true
# opt-level = 0

# [profile.rel-with-deb-info.package."wgpu-types"]
# debug-assertions = false
# debug = true
# opt-level = 0

[profile.dev]
debug-assertions = false
opt-level = 3
[profile.dev.package."*"]
debug-assertions = false
opt-level = 3
