[package]
name = "gfx"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
tracy = [
  "profiling/profile-with-tracy",
  "tracy-client",
  "tracy-client/enable",
  "tracy-client/manual-lifetime",
]
default = []
trace = ["wgpu-core/trace", "wgpu-native/trace"]

[dependencies]
wgpu-native = { path = "../wgpu-native", default-features = false, features = [
  "wgsl",
  "spirv",
  "dx12",
  "metal",
] }
wgpu-core = { path = "../wgpu/wgpu-core" }
wgpu-types = { path = "../wgpu/wgpu-types" }
naga-native = { path = "../naga-native" }
profiling = { version = "1", default-features = false }
tracy-client = { version = "0.17.4", optional = true }

[patch.crates-io]
objc = { git = "https://github.com/shards-lang/rust-objc.git", branch = "shards-0.2.5" }
metal = { git = "https://github.com/shards-lang/metal-rs.git", branch = "shards-0.29.0" }
naga = { path = "../wgpu/naga" }

# Until updates tracy-client to 0.15.0 (https://github.com/aclysma/profiling/pull/44)
profiling = { path = "../profiling" }

[patch."https://github.com/gfx-rs/naga"]
naga = { path = "../wgpu/naga" }

[patch."https://github.com/gfx-rs/wgpu"]
wgpu-types = { path = "../wgpu/wgpu-types" }
wgpu-core = { path = "../wgpu/wgpu-core" }

[build-dependencies]
cbindgen = "0.24.0"

[workspace]
members = []
