[package]
name = "gfx"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[features] 
default = []
tracy = ["profiling/profile-with-tracy", "tracy-client"]

[dependencies]
wgpu-native = { path = "../wgpu-native" }
wgpu-core = { path = "../wgpu/wgpu-core" }
wgpu-types = { path = "../wgpu/wgpu-types" }
naga = { path = "../naga" }
profiling = { version = "1", default-features = false }
tracy-client = { version = "0.15.0", optional = true}

[patch.crates-io]
tracy-client = { git = "https://github.com/nagisa/rust_tracy_client", tag = "tracy-client-v0.15.0" }
naga = { path = "../naga" }
profiling = { path = "../profiling" } # Until updates tracy-client to 0.15.0 (https://github.com/aclysma/profiling/pull/44)

[patch."https://github.com/gfx-rs/naga"]
naga = { path = "../naga" }

[patch."https://github.com/gfx-rs/wgpu"]
wgpu-types = { path = "../wgpu/wgpu-types" }
wgpu-core = { path = "../wgpu/wgpu-core" }

[workspace]
members = []
