#!/bin/bash

echo "Running"

script_dir=$(dirname $0)
root_dir=$(realpath $script_dir/../..)

function control() {
  SHARDS_LOG_FILE=control.log $shards new $script_dir/server/control.shs ${@}
}

set -ex
# control action:run data:"$script_dir/gfx-cube.shs"
# control action:run data:"$script_dir/gfx-texture.shs"
# control action:run data:"$script_dir/gfx-gltf.shs"
control action:run data:"$script_dir/gfx-gltf-anim.shs"