#!/bin/bash

echo "Running"

script_dir=$(dirname $0)
root_dir=$(realpath $script_dir/../..)

function control() {
  SHARDS_LOG_FILE=control.log $shards new $script_dir/server/control.shs ${@}
}

set -ex
(
  sleep 0.5 &&
    control action:preload-files data:"$(cygpath -w $root_dir/assets)" &&
    control action:preload-files data:"$(cygpath -w $root_dir/shards/tests/data)" &&
    control action:preload-files data:"$(cygpath -w $root_dir/external/glTF-Sample-Assets/Models/Avocado)" &&
    control action:preload-files data:"$(cygpath -w $root_dir/external/glTF-Sample-Assets/Models/DamagedHelmet)"
) &
LOG_FLUSH_ON=debug LOG_http=debug SHARDS_LOG_FILE=server.log $shards new $script_dir/server/http-server.shs
