[package]
name = "shards-crypto"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.4.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
tiny-keccak = { version = "2.0.2", features = ["keccak", "sha3"] }
libsecp256k1 = { version = "0.7.1" }
instant = { version = "0.1.12", features = [ "now" ] }
ethereum-types = { version = "0.14.1" }
ethabi = { version = "18.0.0" }
chacha20poly1305 = { version = "0.10.1" }
hex = { version = "0.4.3" }
serde_json = { version = "1.0.95" }
tiny-bip39 = { version = "1.0.0" }
pbkdf2 = { version = "0.12.2", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
hmac = { version = "0.12.1"}
ed25519-dalek = { version = "2.1.1" }
schnorrkel = { version = "0.11.4" }
twox-hash = { version = "1.6.3", features = ["digest_0_10"]}
byteorder = "1.5.0"
digest = "0.10.7"
blake2b_simd = "1.0.2"