[package]
name = "shards-svg"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.4.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
resvg = { version = "0.35.0" }
usvg = { version = "0.35.0" }
# svg crates require 0.10.0 for now
tiny-skia = { version = "0.10.0" }