[package]
name = "shlangbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.1"
shards-lang-core = { path = "../../lang_core" }

[dependencies.xxhash-rust]
version = "0.8.5"
features = ["xxh3"]