[package]
name = "shards-core"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.5.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
hex = { version = "0.4.3" }
bs58 = { version = "0.5.0" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
wasabi_leb128 = { version = "0.4.0" }
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
nanoid = "0.4.0"
rs-snowflake = "0.6.0"
libffi = { version = "3.2.0", optional = true }
dlopen = { version = "0.1.8", optional = true }
serde = "1.0"
serde_yml = "0.0.12"
serde_json = "1.0.102"

[features]
default = []
ffi = ["libffi", "dlopen"]

[patch.crates-io]
chrono = { git = "https://github.com/shards-lang/chrono", rev = "5aaf74235778120b5984b46ced47478c1431d9a0" }
