[package]
name = "test_elements"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { version = "0.18.1" }
egui-gfx = { path = "../../gfx/egui" }