name: Build (Windows 64-bit)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build in Release or Debug?
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
          - Release optimized
      binary-type:
        description: Executable or dynamic library?
        required: false
        default: Exe
        type: choice
        options:
          - Exe
          - Library
      runtime-tests:
        description: Run the runtime tests (Debug only)?
        required: false
        default: false
        type: boolean
      run-tests:
        description: Run the tests?
        required: false
        default: false
        type: boolean
      rust-cache:
        description: Use existing rust cache?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string
      binary-type:
        required: false
        default: Exe
        type: string
      runtime-tests:
        required: false
        default: false
        type: boolean
      run-tests:
        required: false
        default: false
        type: boolean
      rust-cache:
        required: false
        default: true
        type: boolean

jobs:
  #
  # Build shards for Windows
  #
  Windows:
    name: Build (${{ github.event.inputs.binary-type || inputs.binary-type }}, ${{ github.event.inputs.build-type || inputs.build-type }}, 64-bit)
    runs-on: windows-latest
    outputs:
      binary-type: ${{ steps.setup.outputs.binary-type }}
      run-tests: ${{ steps.setup.outputs.run-tests }}
      artifact-name: ${{ steps.setup.outputs.artifact }} ${{ steps.setup.outputs.build-type }}
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          if [ "${{ github.event.inputs.build-type || inputs.build-type }}" == "Release optimized" ]
          then
            echo "build-type=Release" >> $GITHUB_OUTPUT
            echo "optimized=true" >> $GITHUB_OUTPUT
          else
            echo "build-type=${{ github.event.inputs.build-type || inputs.build-type }}" >> $GITHUB_OUTPUT
            echo "optimized=false" >> $GITHUB_OUTPUT
          fi
          echo "binary-type=${{ github.event.inputs.binary-type || inputs.binary-type }}" >> $GITHUB_OUTPUT
          echo "run-tests=${{ github.event.inputs.run-tests || inputs.run-tests }}" >> $GITHUB_OUTPUT
          echo "runtime-tests=${{ github.event.inputs.runtime-tests || inputs.runtime-tests }}" >> $GITHUB_OUTPUT
          echo "rust-cache=${{ github.event.inputs.rust-cache || inputs.rust-cache }}" >> $GITHUB_OUTPUT

          if [ "${{ github.event.inputs.binary-type || inputs.binary-type }}" == "Exe" ]
          then
            echo "build-target=shards" >> $GITHUB_OUTPUT
            echo "artifact-path=build/shards.*" >> $GITHUB_OUTPUT
          else
            echo "build-target=shards-dll" >> $GITHUB_OUTPUT
            echo "artifact-path=build/libshards.*" >> $GITHUB_OUTPUT
          fi

          if [ "${{ github.event.inputs.binary-type || inputs.binary-type }}" == "Exe" ]
          then
            echo "artifact=shards-win64" >> $GITHUB_OUTPUT
          else
            echo "artifact=libshards-win64" >> $GITHUB_OUTPUT
          fi
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: recursive
      - name: Set up rust
        shell: bash
        env:
          RUSTUP_USE_CURL: 1
        run: |
          RUSTUP_TOOLCHAIN=`cat rust.version`-msvc
          echo "RUSTUP_TOOLCHAIN=$RUSTUP_TOOLCHAIN" >> $GITHUB_ENV
          rustup toolchain install $RUSTUP_TOOLCHAIN
      - uses: Swatinem/rust-cache@v2
        if: ${{ steps.setup.outputs.rust-cache == 'true' }}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Set up dev dependencies
        shell: bash
        run: |
          choco install -y --force --version=16.0.6 llvm
          choco install -y cmake ninja
      - name: Build
        env:
          RUST_BACKTRACE: full
        shell: bash
        run: |
          ./bootstrap
          mkdir build
          cd build
          cmake -G Ninja \
            -DSKIP_HEAVY_INLINE=${{ steps.setup.outputs.optimized == 'false' }} \
            "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files\LLVM\bin\clang.exe" \
            "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files\LLVM\bin\clang++.exe" \
            "-DRUST_DEFAULT_TARGET_PATH=C:\shards-rust-target" \
            -DCMAKE_BUILD_TYPE=${{ steps.setup.outputs.build-type }} ..
          echo "Building shards"
          ninja ${{ steps.setup.outputs.build-target }}

          if [ "${{ steps.setup.outputs.runtime-tests }}" == "true" ]
          then
            echo "Building runtime tests"
            ninja test-runtime
            echo "Building graphics tests"
            ninja test-gfx
          fi
      # Minimize disk usage to prevent the next steps getting stuck on glTF models
      - name: Minimize disk usage
        env:
          RUST_BACKTRACE: full
        shell: bash
        run: |
          rm -rf build/src
          rm -rf build/modules
          rm -rf build/lib
          rm -rf build/deps
          rm -rf build/_deps
          rm -rf build/.cache
      - name: Test runtime (Debug)
        if: ${{ steps.setup.outputs.runtime-tests == 'true' && steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cd build
          ./test-runtime
      - name: Checkout glTF-Sample-Models
        # Match with test step below
        if: ${{ steps.setup.outputs.runtime-tests == 'true' && steps.setup.outputs.build-type == 'Debug' }}
        uses: actions/checkout@v3
        with:
          repository: KhronosGroup/glTF-Sample-Models
          path: external/glTF-Sample-Models
          fetch-depth: 1
      - name: Test graphics (Debug)
        if: ${{ steps.setup.outputs.runtime-tests == 'true' && steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cd build
          GFX_BACKEND=D3D12 ./test-gfx
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.setup.outputs.artifact }} ${{ steps.setup.outputs.build-type }}
          path: ${{ steps.setup.outputs.artifact-path }}
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ steps.setup.outputs.artifact }} rejected test data
          path: shards/gfx/tests/data/default/rejected
          if-no-files-found: ignore

  #
  # Test shards for Windows
  #
  Windows-test:
    if: ${{ needs.Windows.outputs.run-tests == 'true' && needs.Windows.outputs.binary-type == 'Exe' }}
    needs: Windows
    name: Test
    runs-on: windows-latest
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "build-type=${{ github.event.inputs.build-type || inputs.build-type }}" >> $GITHUB_OUTPUT
      - name: Change git line endings
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.Windows.outputs.artifact-name }}
          path: build
      - name: Test
        env:
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cd build
          ./shards new ../shards/tests/hello.shs
          echo "Running test: general"
          ./shards new ../shards/tests/general.shs
          echo "Running test: variables"
          ./shards ../shards/tests/variables.edn
          echo "Running test: linalg"
          ./shards new ../shards/tests/linalg.shs
          echo "Running test: loader"
          ./shards ../shards/tests/loader.clj
          echo "Running test: network"
          ./shards new ../shards/tests/network.shs
          echo "Running test: struct"
          ./shards new ../shards/tests/struct.shs
          echo "Running test: flows"
          ./shards new ../shards/tests/flows.shs
          echo "Running test: kdtree"
          ./shards new ../shards/tests/kdtree.shs
          echo "Running test: channels"
          ./shards new ../shards/tests/channels.shs
          echo "Running test: http"
          ./shards new ../shards/tests/http.shs
          echo "Running test: brotli"
          ./shards new ../shards/tests/brotli.shs
          echo "Running test: snappy"
          ./shards new ../shards/tests/snappy.shs
          echo "Running test: expect-like"
          ./shards new ../shards/tests/expect.shs
          # echo "Running test: ws"
          # ./shards ../shards/tests/ws.edn
          echo "Running test: bigint"
          ./shards new ../shards/tests/bigint.shs
          echo "Running test: wasm"
          ./shards ../shards/tests/wasm.clj
          echo "Running test: eth"
          ./shards new ../shards/tests/eth.shs
          echo "Running test: crypto"
          ./shards new ../shards/tests/crypto.shs
          echo "Running test: complex-deserialize"
          ./shards new ../shards/tests/complex-deserialize.shs
          echo "Running test: suspend-resume"
          ./shards new ../shards/tests/suspend-resume.shs
          echo "Running test: help"
          ./shards new ../shards/tests/help.shs
      - name: Test doc samples (non-UI)
        env:
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cd docs/samples
          for i in $(find shards -name '*.edn' \( ! -path '*UI*' ! -path '*GFX*' ! -path '*Dialog*' \));
          do
            echo "Running sample $i";
            ../../build/shards.exe run-sample.edn --file "$i";
          done
      - name: Test doc samples (GFX)
        env:
          GFX_BACKEND: D3D12
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cd docs/samples
          for i in $(find shards -name '*.edn' \( -path '*UI*' -or -path '*GFX*' \));
          do
            echo "Running sample $i";
            ../../build/shards.exe run-sample.edn --looped true --file "$i";
          done
          for i in $(find shards -name '*.shs' \( -path '*UI*' -or -path '*GFX*' \));
          do
            echo "Running sample $i";
            ../../build/shards.exe new run-sample.shs file:"$i";
          done
      - name: Graphics Test
        env:
          GFX_BACKEND: D3D12
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cd build
          echo "Running test: gfx_window"
          ./shards ../shards/tests/gfx-window.edn
          echo "Running test: gfx_cube"
          ./shards new ../shards/tests/gfx-cube.shs
          echo "Running test: gfx_materials"
          ./shards ../shards/tests/gfx-materials.edn
          echo "Running test: ui"
          ./shards ../shards/tests/ui-0.edn
          ./shards ../shards/tests/ui-1.edn
          echo "Running test: egui_demo"
          ./shards new ../shards/tests/egui-demo.shs
          echo "Running test: egui-plot"
          ./shards new ../shards/tests/egui-plot.shs
      - name: Physics Test
        env:
          GFX_BACKEND: D3D12
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cd build
          echo "Running test: physics"
          ./shards ../shards/tests/physics.edn
      - name: Test
        env:
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cd build
          echo "Running test: genetic"
          ./shards new ../shards/tests/genetic.shs
          echo "Running test: time"
          ./shards ../shards/tests/time.edn
          echo "Running test: subwires"
          ./shards new ../shards/tests/subwires.shs
