name: Build (Linux Valgrind)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  #
  # Build shards and run valgrind on Linux
  #
  Linux-valgrind:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev lcov mesa-utils libgtk-3-dev valgrind
          RUSTUP_TOOLCHAIN=`cat rust.version`
          echo "RUSTUP_TOOLCHAIN=$RUSTUP_TOOLCHAIN" >> $GITHUB_ENV
          rustup toolchain install $RUSTUP_TOOLCHAIN
          ./bootstrap
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DUSE_VALGRIND=1 -DSHARDS_WITH_EXTRA_SHARDS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          ninja shards
          ninja test-runtime
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/hello.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/bug1.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/general.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/strings.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/table-compose.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/variables.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/flows.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/linalg.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/return.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/kdtree.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/channels.shs
          SH_IGNORE_CONSISTENT_RESUMER= valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/genetic.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/wasm.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/subwires.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/const-vars.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards ../shards/tests/wires-embed-issue.edn
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/network.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/network-ws.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/capture-logs.shs
          valgrind --exit-on-first-error=no --error-exitcode=1 --fair-sched=yes --leak-check=full ./test-runtime
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/complex-deserialize.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/table-seq-push.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/traits.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/help.shs
          valgrind --exit-on-first-error=yes --error-exitcode=1 --fair-sched=yes ./shards new ../shards/tests/fib.shs
      
      - name: Fetch and send logs of the previous step on failure
        if: failure()
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          LOG_ACCESS_TOKEN: ${{ secrets.LOG_ACCESS_TOKEN }}
        run: |
          echo "Fetching logs of the previous step from GitHub Actions API."
          RUN_ID=${{ github.run_id }}
          
          # Get the current job name directly from the GitHub environment
          JOB_NAME="${{ github.job }}"
      
          # Fetch all jobs for the current run
          JOBS_JSON=$(curl -s -H "Authorization: Bearer $LOG_ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${RUN_ID}/jobs")
      
          # Get the job ID for the current job name
          JOB_ID=$(echo "$JOBS_JSON" | jq -r --arg JOB_NAME "$JOB_NAME" '.jobs[] | select(.name == $JOB_NAME) | .id')
      
          if [ -z "$JOB_ID" ]; then
            echo "Failed to find job ID for the current job name: $JOB_NAME"
            exit 1
          fi
      
          # Get the steps for the job
          STEPS=$(echo "$JOBS_JSON" | jq -r --arg JOB_ID "$JOB_ID" '.jobs[] | select(.id == ($JOB_ID | tonumber)) | .steps')
      
          # Get the second-to-last step, assuming the previous step failed
          PREVIOUS_STEP=$(echo "$STEPS" | jq -r '.[-2].name')
      
          if [ -z "$PREVIOUS_STEP" ]; then
            echo "Failed to find the previous step."
            exit 1
          fi
      
          echo "Previous step that likely failed: $PREVIOUS_STEP"
      
          # Get logs for the previous step
          PREVIOUS_STEP_LOG=$(echo "$STEPS" | jq -r '.[-2].output')
      
          if [ -z "$PREVIOUS_STEP_LOG" ]; then
            echo "Logs not found for the previous step."
            exit 1
          fi
      
          echo "Sending logs of the previous step to DeepSeek API for analysis."
      
          # Truncate log if it's too long (adjust max_length as needed)
          max_length=50000
          truncated_log=$(echo "$PREVIOUS_STEP_LOG" | cut -c 1-$max_length)
      
          # Prepare the messages for the API
          SYSTEM_PROMPT="You are a helpful assistant that analyzes CI build logs to find errors, summarize them, and propose solutions if confident."
          USER_MESSAGE="Here are the CI build logs from the previous step '$PREVIOUS_STEP' (truncated if too long):\n\n$truncated_log"
          
          # Send logs to DeepSeek API
          RESPONSE=$(curl -s https://api.deepseek.com/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $DEEPSEEK_API_KEY" \
            -d @- <<EOF
            {
              "model": "deepseek-chat",
              "messages": [
                {"role": "system", "content": "$SYSTEM_PROMPT"},
                {"role": "user", "content": "$USER_MESSAGE"}
              ],
              "stream": false
            }
            EOF
          )
          
          # Extract the assistant's reply
          ASSISTANT_REPLY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          
          # Print the assistant's reply to the GitHub Actions log
          echo -e "## DeepSeek Analysis:\n$ASSISTANT_REPLY"
