name: Build (Linux)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build in Release or Debug?
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
          - Release optimized
      run-tests:
        description: Run the tests?
        required: false
        default: false
        type: boolean
      rust-cache:
        description: Use existing rust cache?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string
      run-tests:
        required: false
        default: false
        type: boolean
      rust-cache:
        required: false
        default: true
        type: boolean

# Required for <compare> and <=> support
env:
  CC: gcc-11
  CXX: g++-11

jobs:
  #
  # Build shards for linux
  #
  Linux:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: ubuntu-22.04
    outputs:
      build-type: ${{ steps.setup.outputs.build-type }}
      run-tests: ${{ steps.setup.outputs.run-tests }}
      rust-cache: ${{ steps.setup.outputs.rust-cache }}
      artifact-name: shards-linux ${{ steps.setup.outputs.build-type }}
    steps:
      - name: Setup
        id: setup
        run: |
          if [ "${{ github.event.inputs.build-type || inputs.build-type }}" == "Release optimized" ]
          then
            echo "build-type=Release" >> $GITHUB_OUTPUT
            echo "optimized=true" >> $GITHUB_OUTPUT
          else
            echo "build-type=${{ github.event.inputs.build-type || inputs.build-type }}" >> $GITHUB_OUTPUT
            echo "optimized=false" >> $GITHUB_OUTPUT
          fi
          echo "run-tests=${{ github.event.inputs.run-tests || inputs.run-tests }}" >> $GITHUB_OUTPUT
          echo "rust-cache=${{ github.event.inputs.rust-cache || inputs.rust-cache }}" >> $GITHUB_OUTPUT
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 2
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev lcov mesa-utils
          ./bootstrap
          RUSTUP_TOOLCHAIN=`cat rust.version`
          echo "RUSTUP_TOOLCHAIN=$RUSTUP_TOOLCHAIN" >> $GITHUB_ENV
          rustup toolchain install $RUSTUP_TOOLCHAIN
      - uses: Swatinem/rust-cache@v2
        if: ${{ steps.setup.outputs.rust-cache == 'true'}}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Build
        run: |
          mkdir -p build
          cd build

          if [ "${{ steps.setup.outputs.build-type }}" == "Debug" ]; then
            cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=1 -DUSE_UBSAN=ON -DTRACY_ENABLE=ON -DTRACY_TIMER_FALLBACK=ON ..
          else
            cmake -G Ninja -DSKIP_HEAVY_INLINE=${{ steps.setup.outputs.optimized == 'false' }} -DCMAKE_BUILD_TYPE=Release -DUSE_UBSAN=ON ..
          fi

          ninja shards
      - name: Test
        env:
          RUST_BACKTRACE: full
        run: |
          cd build
          chmod +x shards
          ./shards new ../shards/tests/hello.shs
          ./shards ../shards/tests/general.edn
          ./shards ../shards/tests/table-compose.edn
          ./shards ../shards/tests/variables.edn
          ./shards ../shards/tests/subwires.clj
          ./shards ../shards/tests/linalg.clj
          ./shards ../shards/tests/loader.clj
          ./shards ../shards/tests/network.edn
          ./shards ../shards/tests/struct.clj
          ./shards ../shards/tests/flows.edn
          ./shards ../shards/tests/kdtree.clj
          ./shards ../shards/tests/channels.edn
          ./shards ../shards/tests/genetic.clj
          ./shards ../shards/tests/imaging.clj
          ./shards ../shards/tests/http.clj
          ./shards ../shards/tests/ws.edn
          ./shards ../shards/tests/bigint.clj
          ./shards ../shards/tests/brotli.clj
          ./shards ../shards/tests/snappy.clj
          ./shards ../shards/tests/expect.edn
          ./shards ../shards/tests/failures.clj
          ./shards ../shards/tests/wasm.clj
          ./shards ../shards/tests/rust.clj
          ./shards ../shards/tests/crypto.edn
          ./shards ../shards/tests/wire-macro.edn
          ./shards ../shards/tests/const-vars.edn
          ./shards ../shards/tests/branch.edn
          ./shards ../shards/tests/audio.edn
          ./shards ../shards/tests/time.edn
          ./shards ../shards/tests/eth.edn
          ./shards ../shards/tests/take.edn
          ./shards ../shards/tests/casting-numbers.edn
          ./shards ../shards/tests/pure.edn
          # ./shards ../shards/tests/shell.clj
          ./shards ../shards/tests/infos.clj
          ./shards ../shards/tests/many.edn
          ./shards ../shards/tests/events.edn
          ./shards ../shards/tests/tablecase.edn
          ./shards ../shards/tests/types.edn
          ./shards ../shards/tests/complex-deserialize.edn
          ./shards ../shards/tests/db.edn
      - name: Test (Debug)
        # Test that only works in Debug build go there
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: full
        run: |
          cd build
          ./shards ../shards/tests/export-strings.edn
      - name: Test doc samples (non-UI)
        env:
          RUST_BACKTRACE: full
        run: |
          cd docs/samples
          for i in $(find shards -name '*.edn' \( ! -path '*UI*' ! -path '*GFX*' ! -path '*Dialog*' \));
          do
            echo "Running sample $i";
            ../../build/shards run-sample.edn --file "$i";
          done
      - name: Test runtime
        env:
          RUST_BACKTRACE: full
        run: |
          cd build
          ninja test-runtime
          ./test-runtime
      - name: Collect coverage (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        run: |
          mkdir coverage
          # capture
          lcov \
            --capture \
            --directory build/src \
            --directory build/modules \
            --output-file coverage/coverage.info
          # remove external dependencies
          lcov \
            --remove coverage/coverage.info "*/c++/*" "*/boost/*" "*/usr/*" "*/deps/*" "*/shards/mal/*" \
            --output-file coverage/coverage.linux.info
          # convert absolute path to relative path
          sed -i s/${PWD////\\/}/./g coverage/coverage.linux.info
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shards-linux ${{ steps.setup.outputs.build-type }}
          path: build/shards
          if-no-files-found: error
      - name: Upload coverage (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        uses: actions/upload-artifact@v3
        with:
          name: shards-linux-coverage
          path: coverage/coverage.linux.info
          if-no-files-found: error
