name: Build (iOS)

on:
  workflow_dispatch:
    inputs:
      rust-cache:
        description: Use existing rust cache?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      rust-cache:
        required: false
        default: true
        type: boolean

jobs:
  #
  # Build shards for iOS
  #
  iOS:
    runs-on: macos-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "rust-cache=${{ github.event.inputs.rust-cache || inputs.rust-cache }}" >> $GITHUB_OUTPUT
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          brew install cmake clang-format
          ./bootstrap
          RUSTUP_TOOLCHAIN=`cat rust.version`
          echo "RUSTUP_TOOLCHAIN=$RUSTUP_TOOLCHAIN" >> $GITHUB_ENV
          rustup toolchain install $RUSTUP_TOOLCHAIN
          rustup +$RUSTUP_TOOLCHAIN target add aarch64-apple-ios
          rustup +$RUSTUP_TOOLCHAIN target add x86_64-apple-ios
      - uses: Swatinem/rust-cache@v2
        if: ${{ steps.setup.outputs.rust-cache == 'true' }}
      - name: Build iOS
        run: |
          cmake -Bbuild_arm64 -GXcode -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_SYSTEM_PROCESSOR=arm64 -DXCODE_SDK=iphoneos
          cmake --build build_arm64 --target shards-lib -- -arch arm64 -sdk iphoneos
          cmake --build build_arm64 --target cargo-shards-rust-union-rust -- -arch arm64 -sdk iphoneos
      - name: Build visionOS
        run: |
          cmake -Bbuild_sim_visionos -GXcode -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_SYSTEM_NAME=visionOS -DCMAKE_SYSTEM_PROCESSOR=arm64 -DXCODE_SDK=xros
          cmake --build build_sim_visionos --target shards-lib -- -arch arm64 -sdk xros
          cmake --build build_sim_visionos --target cargo-shards-rust-union-rust -- -arch arm64 -sdk xros
