name: Build the documentation

on:
  workflow_call:
    inputs:
      publish:
        required: false
        default: false
        type: boolean

jobs:
  #
  # Run shards documentation samples
  #
  docs-samples:
    # needs: Windows-64bits-Release
    name: Run Samples
    runs-on: windows-latest
    steps:
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
      - name: Download shards
        uses: actions/download-artifact@v3
        with:
          name: shards-win64 Release
          path: docs/samples
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          release: false
          path-type: inherit
      - name: Run samples
        env:
          GFX_BACKEND: D3D12
        shell: msys2 {0}
        run: |
          cd docs/samples
          for i in $(find shards -name '*.edn' \( ! -path '*UI*' ! -path '*GFX*' \));
          do
            echo "Running sample $i";
            ./shards.exe run-sample.edn --file "$i" > >(tee "$i.log");
          done
          for i in $(find shards -name '*.edn' \( -path '*UI*' -or -path '*GFX*' \));
          do
            echo "Running sample $i";
            ./shards.exe run-sample.edn --looped true --file "$i" > >(tee "$i.log");
          done
      - name: Upload samples logs
        uses: actions/upload-artifact@v3
        with:
          name: samples-logs
          path: docs/samples/**/*.log
          if-no-files-found: error

  #
  # Generate shards documentation (markdown)
  #
  docs-markdown:
    # needs: Windows-64bits-Debug
    name: Generate Markdown
    runs-on: windows-latest
    steps:
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
      - name: Download shards
        uses: actions/download-artifact@v3
        with:
          name: shards-win64 Debug
          path: ./
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          release: false
          path-type: inherit
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
      - name: Generate markdown
        shell: msys2 {0}
        run: |
          ./shards.exe docs/generate.edn
      - name: Upload markdown
        uses: actions/upload-artifact@v3
        with:
          name: docs-markdown
          path: |
            docs/docs/reference/shards/**/*.md
            docs/docs/reference/enums/**/*.md
            !docs/docs/reference/enums/index.md
            !docs/docs/reference/shards/index.md
            !docs/docs/reference/shards/types.md
          if-no-files-found: error

  #
  # Build documentation website
  #
  docs-website-build:
    needs: [docs-markdown, docs-samples]
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "publish=${{ github.event.inputs.publish || inputs.publish }}" >> $GITHUB_OUTPUT
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          path: shards
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install mkdocs
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-macros-plugin
      - name: Download markdown
        uses: actions/download-artifact@v3
        with:
          name: docs-markdown
          path: shards/docs/docs/reference
      - name: Download samples logs
        uses: actions/download-artifact@v3
        with:
          name: samples-logs
          path: shards/docs/samples
      - name: Checkout shards-examples
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards-examples
          fetch-depth: 1
          path: shards-examples
      - name: Link tutorials
        run: |
          # note: we link twice because some relative path (esp. include) might be incorrect
          cd shards/docs
          ln -s ../../shards-examples/tutorials/
          cd docs/learn
          ln -s ../../../../shards-examples/tutorials/
      - name: Build website
        if: ${{ steps.setup.outputs.publish != 'true' }}
        run: |
          cd shards/docs
          mkdocs build
      - name: Build & publish website
        if: ${{ steps.setup.outputs.publish == 'true' }}
        run: |
          cd shards/docs
          git config --global user.name "Fragcolor bot"
          git config --global user.email "bot@fragcolor.xyz"
          mkdocs gh-deploy --force --message "Publish documentation from {sha}

          Using MkDocs {version}."
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs-website
          path: shards/docs/site/
          if-no-files-found: error
