name: Build (macOS)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: build in release or debug
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
      runtime-tests:
        description: Run the runtime tests?
        required: true
        default: false
        type: boolean
      run-tests:
        description: Run the tests?
        required: false
        default: false
        type: boolean
      rust-cache:
        description: Use existing rust cache?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string
      runtime-tests:
        required: true
        default: false
        type: boolean
      run-tests:
        required: false
        default: false
        type: boolean
      rust-cache:
        required: false
        default: true
        type: boolean

jobs:
  #
  # Build shards for macOS
  #
  macOS:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: macos-latest
    outputs:
      run-tests: ${{ steps.setup.outputs.run-tests }}
      artifact-name: shards-macos ${{ steps.setup.outputs.build-type }}
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "build-type=${{ github.event.inputs.build-type || inputs.build-type }}" >> $GITHUB_OUTPUT
          echo "runtime-tests=${{ github.event.inputs.runtime-tests || inputs.runtime-tests }}" >> $GITHUB_OUTPUT
          echo "run-tests=${{ github.event.inputs.run-tests || inputs.run-tests }}" >> $GITHUB_OUTPUT
          echo "rust-cache=${{ github.event.inputs.rust-cache || inputs.rust-cache }}" >> $GITHUB_OUTPUT
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          brew install cmake ninja clang-format
          ./bootstrap
          rustup toolchain install nightly
          rustup default nightly
      - uses: Swatinem/rust-cache@v2
        if: ${{ steps.setup.outputs.rust-cache == 'true' }}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DSKIP_HEAVY_INLINE=1 -DCMAKE_BUILD_TYPE=${{ steps.setup.outputs.build-type }} -DUSE_UBSAN=ON -DTRACY_ENABLE=ON -DTRACY_TIMER_FALLBACK=ON ..
          ninja shards
      - name: Test runtime (Debug)
        if: ${{ steps.setup.outputs.runtime-tests == 'true' && steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: full
        run: |
          cd build
          ninja test-runtime
          ./test-runtime
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shards-macos ${{ steps.setup.outputs.build-type }}
          path: build/shards
          if-no-files-found: error

  #
  # Test shards on macOS
  #
  macOS-test:
    if: ${{ needs.macOS.outputs.run-tests == 'true' }}
    needs: macOS
    name: Test
    runs-on: macos-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "build-type=${{ github.event.inputs.build-type || inputs.build-type }}" >> $GITHUB_OUTPUT
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.macOS.outputs.artifact-name }}
          path: build
      - name: Test
        env:
          RUST_BACKTRACE: full
        run: |
          cd build
          chmod +x shards
          ./shards ../src/tests/general.edn
          ./shards ../src/tests/variables.edn
          ./shards ../src/tests/subwires.clj
          ./shards ../src/tests/linalg.clj
          ./shards ../src/tests/loader.clj
          ./shards ../src/tests/network.edn
          ./shards ../src/tests/struct.clj
          ./shards ../src/tests/flows.edn
          ./shards ../src/tests/kdtree.clj
          ./shards ../src/tests/channels.clj
          ./shards ../src/tests/imaging.clj
          ./shards ../src/tests/http.clj
          # ./shards ../src/tests/ws.edn
          ./shards ../src/tests/bigint.clj
          ./shards ../src/tests/brotli.clj
          ./shards ../src/tests/snappy.clj
          ./shards ../src/tests/expect-like.edn
          ./shards ../src/tests/wasm.clj
          ./shards ../src/tests/infos.clj
          ./shards ../src/tests/rust.clj
          ./shards ../src/tests/crypto.edn
          ./shards ../src/tests/wire-macro.edn
          ./shards ../src/tests/branch.edn
          ./shards ../src/tests/audio.edn
          ./shards ../src/tests/time.edn
          ./shards ../src/tests/eth.edn
          ./shards ../src/tests/many.edn
          ./shards ../src/tests/events.edn
          ./shards ../src/tests/complex-deserialize.edn
      - name: Test doc samples (non-UI)
        env:
          RUST_BACKTRACE: full
        run: |
          cd docs/samples
          for i in $(find shards -name '*.edn' \( ! -path '*UI*' ! -path '*GFX*' ! -path '*Dialog*' \));
          do
            echo "Running sample $i";
            ../../build/shards run-sample.edn --file "$i";
          done
