name: Build (Linux Valgrind)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  #
  # Build shards and run valgrind on Linux
  #
  Linux-valgrind:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: recursive
      # TODO: use docker actions to build and run
      #       see:
      #         - https://github.com/docker/build-push-action
      #         - https://github.com/addnab/docker-run-action
      - name: Build docker
        run: |
          docker build --build-arg RUSTUP_TOOLCHAIN=`cat rust.version` -f docker/linux/Dockerfile -t shards-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` .
      - name: Build and Test
        run: |
          docker run --rm -t --cap-add=SYS_PTRACE -u`id -u`:`id -g` shards-test bash -c "./bootstrap && mkdir build && cd build && cmake -G Ninja -DSHARDS_VALGRIND=1 -DUSE_VALGRIND=1 -DSHARDS_WITH_EXTRA_SHARDS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && ninja shards && ninja test-runtime && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/bug1.edn && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/general.edn && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/variables.edn && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/flows.edn && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/linalg.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/kdtree.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/channels.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/genetic.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/wasm.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/subwires.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/const-vars.edn && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/wires-embed-issue.edn && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/network.edn && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/capture-logs.edn && valgrind --exit-on-first-error=yes --error-exitcode=1 --leak-check=full ./test-runtime && valgrind --exit-on-first-error=yes --error-exitcode=1 ./shards ../src/tests/complex-deserialize.edn"
