name: CI

on:
  push:
    branches:
      - devel
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      rust-cache:
        description: Use existing rust cache?
        required: false
        default: false
        type: boolean

jobs:
  Setup:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  cancel-previous-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: shards-lang/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ secrets.TOKEN }}

  #
  # Build shards for emscripten
  #
  wasm32-emscripten-mt:
    needs: Setup
    uses: ./.github/workflows/build-wasm.yml
    secrets: inherit
    with:
      threading: mt
      run-tests: true

  #
  # Build shards for linux
  #
  Linux-Debug:
    needs: Setup
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      build-type: Debug
      run-tests: true
  Linux-Release:
    needs: Setup
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      build-type: Release
      run-tests: true
  MacOS-GPU:
    needs: Setup
    uses: ./.github/workflows/test-macos-gpu.yml
    secrets: inherit
    with:
      build-type: Debug
  Codecov:
    needs: [Linux-Debug, MacOS-GPU]
    uses: ./.github/workflows/codecov.yml
    secrets: inherit

  #
  # Build shards and run valgrind on Linux
  #
  Linux-valgrind:
    needs: Setup
    uses: ./.github/workflows/build-linux-valgrind.yml
    secrets: inherit

  #
  # Build shards for Windows
  #
  Windows-Debug:
    needs: Setup
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      build-type: Debug
      runtime-tests: true
      run-tests: true
  Windows-Release:
    needs: Setup
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      build-type: Release
      run-tests: true

  #
  # Build the documentation
  #
  docs:
    needs: [Windows-Debug, Windows-Release]
    uses: ./.github/workflows/build-doc.yml
    secrets: inherit
    with:
      publish: ${{ github.ref == 'refs/heads/devel' && github.event_name == 'push' }}

  #
  # Build shards for macOS
  #
  macOS-Debug:
    needs: Setup
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      build-type: Debug
      runtime-tests: true
      run-tests: true
  macOS-Release:
    needs: Setup
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      build-type: Release
      runtime-tests: true
      run-tests: true

  #
  # Build shards for iOS
  #
  iOS:
    needs: Setup
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
