name: CI

on: [push, pull_request]

jobs:
  ciWasmDbg:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        git submodule update --init --recursive
        sudo apt-get -y install build-essential git cmake wget ninja-build
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        cd .. && mkdir external && cd external
        wget -nv https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz
        tar xzf boost_1_74_0.tar.gz
    - name: Build
      run: |
        source emsdk/emsdk_env.sh
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake .. 
        ninja cbl
    - name: Test
      run: |
        cd build
        node --experimental-wasm-threads --experimental-wasm-bulk-memory cbl.js -e '(do (def Root (Node)) (schedule Root (Chain "x" (Pause 2.0) (Msg "Hello") 0 (Exit))) (run Root 0.1))'
    - uses: actions/upload-artifact@master
      with:
        name: cbl-wasm
        path: |
          build/cbl.wasm
          build/cbl.js
          build/cbl.html

  ciLinuxDbg:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        git submodule update --init --recursive
        sudo apt-get -y install build-essential git cmake wget clang ninja-build libboost-all-dev xorg-dev libdbus-1-dev libssl-dev lcov xvfb
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=1 .. 
        ninja cbl
    - name: Test
      run: |
        cd build
        ./cbl ../src/tests/general.clj
        ./cbl ../src/tests/variables.clj
        ./cbl ../src/tests/subchains.clj
        ./cbl ../src/tests/linalg.clj
        ./cbl ../src/tests/loader.clj
        ./cbl ../src/tests/network.clj
        ./cbl ../src/tests/struct.clj
        ./cbl ../src/tests/flows.clj
        ./cbl ../src/tests/kdtree.clj
        ./cbl ../src/tests/channels.clj
        ./cbl ../src/tests/genetic.clj
        ./cbl ../src/tests/imaging.clj
        ./cbl ../src/tests/http.clj
        ./cbl ../src/tests/ws.clj
        ./cbl ../src/tests/bigint.clj
        ./cbl ../src/tests/brotli.clj
        Xvfb :1 -screen 1 1600x1200x16&
        DISPLAY=:1 ./cbl ../src/tests/bgfx.clj
    - name: CodeCov
      run: |
        mkdir coverage
        lcov --capture --directory build/CMakeFiles/cb_static.dir --output-file coverage/coverage.info
        lcov --remove coverage/coverage.info */c++/* */boost/* */usr/* */deps/* --output-file coverage/coverage.f.info
        genhtml coverage/coverage.f.info --output-directory coverage/output
        bash <(curl -s https://codecov.io/bash) -f coverage/coverage.f.info || echo "Codecov did not collect coverage reports"
    - uses: actions/upload-artifact@master
      with:
        name: coverage
        path: coverage/output

  ciLinuxRel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Fetch submodules
      run: |
        git submodule update --init --recursive
    - uses: chainblocks/Publish-Docker-Github-Action@master
      name: Build and upload to hub devel image
      with:
        name: chainblocks/devenv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/linux/Dockerfile
        tags: "latest"
    - name: Build and Test
      run: |
        docker run --name chainblocks -t --cap-add=SYS_PTRACE chainblocks/devenv:latest bash -c "mkdir build && cd build && cmake -G Ninja -DFORCE_CORE2=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && ninja cbl && ./cbl ../src/tests/general.clj && ./cbl ../src/tests/variables.clj && ./cbl ../src/tests/linalg.clj && ./cbl ../src/tests/channels.clj"
        mkdir build
        docker cp chainblocks:/home/chainblocks/repo/build/cbl ./build/cbl
    - uses: chainblocks/Publish-Docker-Github-Action@master
      name: Build and upload to hub runtime image
      with:
        name: chainblocks/cbl
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/linux/Dockerfile-runtime
        tags: "latest"

  ciLinuxValgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        git submodule update --init --recursive
        docker build -f docker/linux/Dockerfile -t chainblocks-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` .
    - name: Test
      run: |
        docker run --rm -t --cap-add=SYS_PTRACE -u`id -u`:`id -g` chainblocks-test bash -c "mkdir build && cd build && cmake -G Ninja -DCB_NO_BIGINT_BLOCKS=1 -DUSE_VALGRIND=1 -DBUILD_CORE_ONLY=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && ninja cbl && valgrind --exit-on-first-error=yes --error-exitcode=1 ./cbl ../src/tests/general.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./cbl ../src/tests/variables.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./cbl ../src/tests/flows.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./cbl ../src/tests/linalg.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./cbl ../src/tests/channels.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./cbl ../src/tests/genetic.clj && valgrind --exit-on-first-error=yes --error-exitcode=1 ./cbl ../src/tests/http.clj"

  ciWindowsRel:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive
    - uses: chainblocks/setup-msys2@v2
      with:
        msystem: MINGW64
        release: false
    - run: msys2 ./build-win.sh Release
    - uses: actions/upload-artifact@master
      with:
        name: cbl-win64
        path: build/cbl.exe

  ciWindowsRel32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive
    - uses: chainblocks/setup-msys2@v2
      with:
        msystem: MINGW32
        release: false
    - run: msys2 ./build-win32.sh Release
    - uses: actions/upload-artifact@master
      with:
        name: cbl-win32
        path: build/cbl.exe

  ciWindowsDbg:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive
    - uses: chainblocks/setup-msys2@v2
      with:
        msystem: MINGW64
        release: false
    - run: msys2 ./build-win.sh Debug

  ciWindowsDbg32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init --recursive
    - uses: chainblocks/setup-msys2@v2
      with:
        msystem: MINGW32
        release: false
    - run: msys2 ./build-win32.sh Debug

  ciMacDbg:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        brew install boost cmake ninja clang-format
    - name: Build
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake -G Ninja -DFORCE_CORE2=1 -DCMAKE_BUILD_TYPE=Debug ..
        ninja cbl
    - name: Test
      run: |
        cd build
        ./cbl ../src/tests/general.clj
        ./cbl ../src/tests/variables.clj
        ./cbl ../src/tests/subchains.clj
        ./cbl ../src/tests/linalg.clj
        ./cbl ../src/tests/loader.clj
        ./cbl ../src/tests/network.clj
        ./cbl ../src/tests/struct.clj
        ./cbl ../src/tests/flows.clj
        ./cbl ../src/tests/kdtree.clj
        ./cbl ../src/tests/channels.clj
        ./cbl ../src/tests/genetic.clj
        ./cbl ../src/tests/imaging.clj
        ./cbl ../src/tests/http.clj
        ./cbl ../src/tests/ws.clj
        ./cbl ../src/tests/bigint.clj
        ./cbl ../src/tests/brotli.clj

  ciMacRel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        brew install boost cmake ninja clang-format
    - name: Build
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake -G Ninja -DFORCE_CORE2=1 -DCMAKE_BUILD_TYPE=Release ..
        ninja cbl
    - name: Test
      run: |
        cd build
        ./cbl ../src/tests/general.clj
        ./cbl ../src/tests/variables.clj
        ./cbl ../src/tests/subchains.clj
        ./cbl ../src/tests/linalg.clj
        ./cbl ../src/tests/loader.clj
        ./cbl ../src/tests/network.clj
        ./cbl ../src/tests/struct.clj
        ./cbl ../src/tests/flows.clj
        ./cbl ../src/tests/kdtree.clj
        ./cbl ../src/tests/channels.clj
        ./cbl ../src/tests/genetic.clj
        ./cbl ../src/tests/imaging.clj
        ./cbl ../src/tests/http.clj
        ./cbl ../src/tests/ws.clj
        ./cbl ../src/tests/bigint.clj
        ./cbl ../src/tests/brotli.clj
  
  rustBuild:
    needs: ciLinuxRel
    name: Rust check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          docker run --rm -t --cap-add=SYS_PTRACE chainblocks/devenv:latest bash -c "sh rust/docker/run_linux.sh"
