name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Deps
      run: |
        sudo apt-get install -y libboost-filesystem-dev libboost-context-dev cmake ninja
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DBUILD_CORE_ONLY=1 -DCMAKE_BUILD_TYPE=Debug ..
        ninja cbl
    - name: Run
      run: |
        ./cbl ../src/tests/general.clj
        ./cbl ../src/tests/variables.clj
        ./cbl ../src/tests/subchains.clj
        ./cbl ../src/tests/linalg.clj
