name: Publish a release

on:
  # push:
  #   tags:
  #     - "v*.*"
  workflow_dispatch:

jobs:
  Setup:
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  Windows:
    needs: Setup
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      binary-type: Exe
      build-type: Release optimized
      run-tests: false

  Linux:
    needs: Setup
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      build-type: Release optimized
      run-tests: false

  macOS:
    needs: Setup
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      build-type: Release
      run-tests: false

  Publish:
    needs: [Windows, Linux, macOS]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: shards-win64 Release
          path: windows
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: shards-linux Release
          path: linux
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: shards-macos Release
          path: macOS
      - name: Create release files
        shell: bash
        run: |
          # Linux
          pushd linux
          tar -czf ../shards-linux-${{ github.ref_name }}.tar.gz shards
          popd

          # macOS
          pushd macOS
          tar -czf ../shards-macOS-${{ github.ref_name }}.tar.gz shards
          popd

          # Windows
          sudo apt install zip
          pushd windows
          zip ../shards-windows-${{ github.ref_name }}.zip shards.exe
          popd
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          files: |
            shards-linux-${{ github.ref_name }}.tar.gz
            shards-macOS-${{ github.ref_name }}.tar.gz
            shards-windows-${{ github.ref_name }}.zip
