name: Test (Linux/GPU)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build in Release or Debug?
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
      clean-workspace:
        description: Remove the workspace folder before checking out?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string
      clean-workspace:
        required: false
        default: false
        type: boolean

jobs:
  #
  # Build shards for linux
  #
  Linux:
    name: Test (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: self-hosted
    steps:
      - name: Setup
        id: setup
        run: |
          echo "::set-output name=build-type::${{ github.event.inputs.build-type || inputs.build-type }}"
      - name: Clean workspace
        if: ${{ github.event.inputs.clean-workspace == 'true' || inputs.clean-workspace == 'true' }}
        run: |
            rm -rf $GITHUB_WORKSPACE
            mkdir $GITHUB_WORKSPACE
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 2
          submodules: recursive
      - name: Set up dependencies
        run: |
          ./bootstrap
      - name: Build
        run: |
          cmake -Bbuild -G Ninja -DCODE_COVERAGE=1 -DCMAKE_BUILD_TYPE=${{ steps.setup.outputs.build-type }}
          cmake --build build --target shards test-gfx
      - name: Checkout glTF-Sample-Models
        uses: actions/checkout@v3
        with:
          repository: KhronosGroup/glTF-Sample-Models
          path: external/glTF-Sample-Models
          fetch-depth: 1
      - name: Download MobileNet v2
        run: |
          cd src/tests
          wget https://github.com/onnx/models/raw/main/vision/classification/mobilenet/model/mobilenetv2-7.onnx
      - name: Test (GPU)
        env:
          RUST_BACKTRACE: 1
        run: |
          set -e
          export DISPLAY=:1
          Xvfb "$DISPLAY" &

          echo "Running graphics library tests"
          GFX_TEST_PLATFORM_ID="github-linux" build/test-gfx -r JUnit --out test-gfx.xml

          echo "\n"
          echo "Running graphics test scripts"
          for i in $(find src/tests -name 'gfx*.edn');
          do
            echo "Running $i"
            build/shards "$i"
          done

          echo "Running UI"
          build/shards src/tests/ui.edn

          echo "Running egui demo"
          build/shards src/tests/egui-demo.edn

          echo "Running imgui demo"
          build/shards src/tests/imgui-demo.edn
      - name: Test doc samples (UI)
        env:
          RUST_BACKTRACE: 1
        run: |
          set -e
          export DISPLAY=:1
          Xvfb "$DISPLAY" &

          cd docs/samples
          for i in $(find shards -name '*.edn' -path '*UI*');
          do
            echo "Running sample $i";
            ../../build/shards run-sample.edn --file "$i";
          done
      - name: Coverage (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        run: |
          mkdir coverage
          lcov --capture --directory build/src --output-file coverage/coverage.info
          lcov --remove coverage/coverage.info "*/c++/*" "*/boost/*" "*/usr/*" "*/deps/*" "*/src/mal/*" --output-file coverage/coverage.f.info
          genhtml coverage/coverage.f.info --output-directory coverage/output
          bash <(curl -s https://codecov.io/bash) -f coverage/coverage.f.info || echo "Codecov did not collect coverage reports"
      - name: Upload coverage (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        uses: actions/upload-artifact@v3
        with:
          name: shards-linux-gpu-coverage
          path: |
            coverage
            test-gfx.xml
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: shards-linux-gpu rejected test data
          path: src/gfx/tests/data/github-linux/rejected
          if-no-files-found: ignore
